### ISSUE TITLE
[Revoke model] Need to add the length limitation for the `reason` field in the `revoke-model` command.

### ISSUE THREAD

**Issue by julia-aksyanova** [zigbee-alliance/distributed-compliance-ledger#10]
Severity:
enhancement

Build info:
0505970

Overview:
Need to add the length limitation for the `reason` field in the revoke-model command (zblcli tx compliance revoke-model --vid=<uint16> --pid=<uint16> --certification-type=<zb> --revocation-date=<rfc3339 encoded date> --reason=<resaon_info> --from=<account>).
Actually, the `reason` field is not limited.
It is suggested to make the next limitation that must be discussed:
 - the maximum available length for the `reason` field is about 255-15000 symbols.

**Comment by ashcherbakov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/199
