### ISSUE TITLE
Load Tests: Run against a local pool

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#102]
- Prepare a Test Plan
   - Consider minimally sufficient set of tests. For example, run X client AWS machines, each runs both write and read reqs as much as possible 
- Run the tests (see #94) against a pool created via IaC done in the deployment Epic.
- Analyse results

**Comment by hawk248** [comment]
Pre 1.0

**Comment by abdulla-ashurov** [comment]
**Plan of attack:**

1. Try to run and check existing load tests.
2. Add the ability to rerun the test as many times as possible without re-running the servers - so that we can really load our servers.
3. Try to run the above steps on real machines and analyze the work process.

**Comment by abdulla-ashurov** [comment]
Plan of attack by Write Load Tests:

1. Compare writing models, which one is faster, and get the option that is faster:
    - Direct writing models
    - Generate models in a file and write models from a file

**Comment by uabjabborov** [comment]
@abdulla-ashurov please update the docs according to your changes

**Comment by uabjabborov** [comment]
Load tests report is available here https://docs.google.com/document/d/1mXxCABxAUYPRYxPkl7WNbUi9tyfyl1opoloYIWhjPAA/edit
