### ISSUE TITLE
[Revoke model] Revoke command is successfully executed for invalid pair of `vid` and `pid` parameters.

### ISSUE THREAD

**Issue by julia-aksyanova** [zigbee-alliance/distributed-compliance-ledger#12]
Severity:
major

Build info:
0505970

Steps to reproduce:
1. Add to the system model-info with valid `vid` and `pid` (`zblcli tx modelinfo add-model...`).
2. Add test-result for this model: use the same `vid` and `pid` parameters (`zblcli tx compliancetest add-test-result...`).
3. Certify this model: use the same `vid` and `pid` parameters  (`zblcli tx compliance certify-model...`).
4. Revoke the model (`zblcli tx compliance revoke-model...`) but:
 - make a typo in `vid` and\or `pid` parameters;
 - or enter any not-existing `vid` and\or `pid` parameters.
5. Look at the results of the revoke command execution.

Actual results:
The revoke command is successfully executed.

Expected results:
The error should appear if the revoke command contains not-existing `vid` and `pid` parameters: "No model info associated with the vid=<value> and pid=<value> on the ledger.".

Additional info:
If the user makes revocation with invalid pair of `vid` and `pid` parameters and then he\she decides to certify the same invalid pair of `vid` and `pid`, the certification is successfully executed.
But if check the info about mpdel (`zblcli query modelinfo model --vid=<value> --pid=<value>`), there is no info about this model.
![revocation-and-certification-invalid-vid-and-pid](https://user-images.githubusercontent.com/70644510/92148299-08f9a300-ee25-11ea-8d2e-a1ed82d71bbf.png)

![image](https://user-images.githubusercontent.com/70644510/92148216-eebfc500-ee24-11ea-880b-75b7ccf14092.png)

**Comment by ashcherbakov** [comment]
Fixed in https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/73
