### ISSUE TITLE
[Certify model] Need to remove the possibility to certify model several times from different accounts.

### ISSUE THREAD

**Issue by julia-aksyanova** [zigbee-alliance/distributed-compliance-ledger#13]
Severity:
major

Build info:
0505970

Precondition:
The system should have two or more users with the `ZBCertificationCenter` role.

Steps to reproduce:
1. Add to the system model-info with valid vid and pid (`zblcli tx modelinfo add-model...`).
2. Add test-result for this model: use the same vid and pid parameters (`zblcli tx compliancetest add-test-result...`).
3. Certify this model using one account with the `ZBCertificationCenter` role: use the same vid and pid parameters (`zblcli tx compliance certify-model...`).
4. Try to certify the same pair of vid and pid:
 a) using the same account with the `ZBCertificationCenter` role (from step 3);
 b) using another account with the `ZBCertificationCenter` role (not the same as in step 3).
5. Look at the result of the command execution.

Actual results:
The second certification command for the same pair of the `vid` and `pid` is successfully executed.

Expected results:
a) When the same account with the `ZBCertificationCenter` role (from step 3) is used at the second request, the confirmation message should appear: "override the existing certification info [y/N]: " (message should be discussed). 
b) When another account with the `ZBCertificationCenter` role (not the same as in step 3)  is used at the second request, error message should appear info the results: "Model with vid=<value> and pid=<value> is already certified on the ledger."(message should be discussed).

**Comment by ashcherbakov** [comment]
Fixed in https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/70
