### ISSUE TITLE
Get rid of boilerplate types defined in integration_tests/utils/types.go

### ISSUE THREAD

**Issue by askolesov** [zigbee-alliance/distributed-compliance-ledger#19]
`integration_tests/utils/types.go` contains a number of struct types repeating the shapes of struct types from application modules but with some distinctions. These types are used for unmarshalling by `encoding/json` of data previously marshalled by `tendermint/go-amino`. The distinctions are as follows:
- types in `integration_tests/utils` use string fields where the corresponding types from application modules use 64-bit integer fields (because Amino codec intentionally marshals 64-bit integers to JSON as strings, while `encoding/json` does not perform the backward conversion),
- types in `integration_tests/utils` omit fields of interface types (because Amino codec marshals such fields as interface values, i.e. value-type tuples, but `encoding/json` does not handle such representation).

Consider ways to get rid of using these boilerplate types for integration tests. As an option, integration tests might use Amino codec (as the node/client implementation does) with registering necessary interface / concrete types in the codec. The code from the implementation can be re-used for registering types in the codec.

By @spivachuk

**Comment by ashcherbakov** [comment]
Deprecated after migration to the latest cosmos-sdk
