### ISSUE TITLE
Correct handling of errors from CLIContext.queryStore

### ISSUE THREAD

**Issue by askolesov** [zigbee-alliance/distributed-compliance-ledger#20]
Now the client implementation treats an error returned by `CLIContext.QueryStore` as the entry absence, the same as it treats nil result of `CLIContext.QueryStore`. However, only nil result of `CLIContext.QueryStore` actually means the entry absence. An error is returned in case of the query failure (e.g. proof verification failure, etc).

In each place, where `QueryStore` is used, separate handling of an error from handling of nil result and provide proper handling for an error.

By @spivachuk

**Comment by ashcherbakov** [comment]
Already done in the recent DCL. See `QueryWithProof` function.
