### ISSUE TITLE
Update of Cosmos SDK

### ISSUE THREAD

**Issue by askolesov** [zigbee-alliance/distributed-compliance-ledger#22]
The current version of Cosmos SDK (v0.37.4) is highly outdated. We need to update to the latest one. The more changes we make and more time we wait the more complex update process will be.
* Current version: v0.39.1
* See changelog for migration: https://github.com/cosmos/cosmos-sdk/blob/master/CHANGELOG.md
* Migration branch: feature/cosmos-update

**Comment by ashcherbakov** [comment]
Duplicates #99
