### ISSUE TITLE
Deployment: IaC - Ansible

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#220]
**Acceptance Criteria**
- Replace existing [run_dcl_node](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/deployment/scripts/run_dcl_node) scripts by Ansible scripts for nodes provisioning according to the Design docs created in #246. 
- Make sure we set common params for all node types, such as the interval for empty blocks (change from 5 secs (current default) to a greater value (for example 10 mins)).

**Comment by uabjabborov** [comment]
https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/339
