### ISSUE TITLE
Deployment: Health&Monitoring 

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#221]
**Acceptance Criteria**
- Define ways for health and monitoring based on #100 and https://github.com/zigbee-alliance/distributed-compliance-ledger/wiki/DCL-MainNet-Deployment
- Define how to analyze node logs
  -  ELK stack?
- Define how to monitor metrics
  - Prometheus + Graphana?
- Define the metrics to be monitored
- Define metric-based alerts
- Implement scripts and/or IaC for logs
- Implement scripts and/or IaC for metrics
- Implement scripts and/or IaC for alerts

**Comment by uabjabborov** [comment]
**Define how to monitor metrics:**
1. Enable Prometheus metrics in the Tendermint config 
https://docs.tendermint.com/master/nodes/metrics.html
2. For AWS use AMP (Amazon Managed Service for Prometheus) to collect Prometheus metrics and visualize using Grafana
https://aws.amazon.com/blogs/opensource/using-amazon-managed-service-for-prometheus-to-monitor-ec2-environments/

**Comment by uabjabborov** [comment]
**Define how to analyze node logs:**

We can use AWS cloudwatch agent to collect `cosmovisor` service logs and it to AWS CloudWatch
https://devopscube.com/how-to-setup-and-push-serverapplication-logs-to-aws-cloudwatch/

**Comment by uabjabborov** [comment]
PR #366
