### ISSUE TITLE
Deployment: IaC - Terraform

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#222]
**Acceptance Criteria**
- Implement Terraform part of the IaC as designed in #246.

**Comment by uabjabborov** [comment]
PoA:
1. Provide `terraform` scripts to roll out an AWS infrastructure by modules
2. Provide `ansible` scripts to provision a node depending on a node type (validator, observer, sentry, seed)

**Comment by uabjabborov** [comment]
PR https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/332
