### ISSUE TITLE
[General] The new input line should not be presented as the continuation of the error when the `from` parameter contains a not existing account.

### ISSUE THREAD

**Issue by askolesov** [zigbee-alliance/distributed-compliance-ledger#26]
Severity: minor

Build info: 1b992833

Steps to reproduce:
1. Enter any command in CLI which contains `from` parameter: for example, add a new account, approve the account, add model info, add test info, etc.
2. Enter incorrect (not existing) account in the `from` parameter.
3. Send the command.
4. Look at the received result.

Actual results:
The error is returned. The new input line is presented as the continuation of the error.

Expected results:
The error is returned. And the new input line should begin with a new line.
![image](https://user-images.githubusercontent.com/21123752/92369910-451d5400-f102-11ea-869c-2df0130cf348.png)

By @julia-aksyanova

**Comment by ashcherbakov** [comment]
Not reproduced after migration to the latest cosmos sdk
