### ISSUE TITLE
Defect: unify camel or snake case usage in the REST API

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#265]
Besides #264, there are inconsistencies in the DCL REST API: in some cases (query response root elements) camel case is used for keys, but in some cases (all internal structs) snake case (`_`) is used.

This is actually how [Starport](https://github.com/tendermint/starport) generates the code, so it may mean a bug in the starwort itself. Nevertheless, we should consider fixing it.

**Acceptance criteria**
- Unify all REST API: either camel or snake case
- Make sure that openapi is correct
- Extend [DEV docs](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/README-DEV.md) mentioning how to generate unified API taking into account possible issues in starport.
- Fix typo in the API (see https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/259/files)
- [Optional] Investigate why starport generates the code like this.

**Comment by ashcherbakov** [comment]
So, currently we have a mix of snake and camel case:
- All responses in query.proto are in camel case, while requests are in camel case
- Some entities (model, PKI, compliance) are in snake case, some entities (validator, vendor info, auth) are in camel case
- cosmos-sdk default entities are in snake case

Actually it wasn't intentional. We always used [starport](https://github.com/tendermint/starport) for code scaffolding and generation.
And it turned out (bad luck), that starport had a bug at the time when we were generating the code, so some of the models have been generated in snake case....
- snake case introduced: https://github.com/tendermint/starport/pull/1844
- snake case reverted: https://github.com/tendermint/starport/commit/4a6774d547d3dd7c5f2e358a65db46e377fd8ac8.

It looks like a correct fix would be to use camel case (although cosmo sdk default entities will still be in snake case). But in any case it will be a breaking change for the current Test Net and the data there.

**Comment by ankur325** [comment]
We should be fine with changing the names as this will not break any existing data, as all data Marshalled from its proto structure. https://developers.google.com/protocol-buffers/docs/encoding#structure

**Comment by ashcherbakov** [comment]
Yes, you are right, we should be good with the data. The only thing is that it will be a breaking change from the API (REST/gRPC JSONs) point of view. Hopefully it should be fine...

**Comment by abdulla-ashurov** [comment]
1. View all files in a proto folder.
2. Find incorrect entity when starport generates snake case and change these are fields to camel case.
