### ISSUE TITLE
[Propose add account] It should be impossible to send the `propose-add-account` that does not contain the `role` parameter.

### ISSUE THREAD

**Issue by askolesov** [zigbee-alliance/distributed-compliance-ledger#27]
Severity: major

Build info: 1b992833

Steps to reproduce:

1. Enter `propose-add-account` command which contains:
 - valid `address` and `pubkey` parameters;
 - valid `from` parameter;
 - `role` parameter does not exist in this request.

Example of this command: `zblcli tx auth propose-add-account --address=<valid_value> --pubkey=<valid_value> --from=<valid_value>` 

2. Send the command.
3. Look at the received result.

Actual results: 
The account is successfully added and the actual status of it is proposed. 
Also, other Trustee accounts can approve it without any problems.

Expected results: 
It should be impossible to send the `propose-add-account` that does not contain the `role` parameter.

By @julia-aksyanova

**Comment by ashcherbakov** [comment]
Fixed during migration to the latest cosmo-sdk
