### ISSUE TITLE
More human friendly way to display Matter OIDs in the certificates

### ISSUE THREAD

**Issue by robszewczyk** [zigbee-alliance/distributed-compliance-ledger#270]
Currently Matter spec provides for two Matter-specific OIDs to be embedded in x509 certificates:

```
1.3.6.1.4.1.37244.2.1  VID
1.3.6.1.4.1.37244.2.2 PID
```

The `pkix.go` library used by DCL recognizes only a small subset of OIDs:

```
	"2.5.4.6":  "C",
	"2.5.4.10": "O",
	"2.5.4.11": "OU",
	"2.5.4.3":  "CN",
	"2.5.4.5":  "SERIALNUMBER",
	"2.5.4.7":  "L",
	"2.5.4.8":  "ST",
	"2.5.4.9":  "STREET",
	"2.5.4.17": "POSTALCODE",
```

All other OIDs are printed in a rather human-hostile format:
```
numericOID=#hex.EncodeToString(derBytes)
```

so instead of  relatively readable entries such as `VID = 24582` we are left with `1.3.6.1.4.1.37244.2.1=#130436303036`

Please add a more human-readable way to print the `VID` and `PID` in Matter x509 certs in the DCL

**Comment by hawk248** [comment]
Investigate to see if this a breaking change. If breaking, it will be Pre Mainnet 1.0.
The existing PAA in testnet will be left as they are.

**Comment by abdulla-ashurov** [comment]
@robszewczyk We should show VID and PID in format decimal or hex?
In my opinion, we should show VID and PID in hex format, because we're going to change VID to format hex in ticket #272  (https://github.com/zigbee-alliance/distributed-compliance-ledger/issues/272)

**Comment by uabjabborov** [comment]
@robszewczyk Could you also provide additional certificates with PID for testing? Or provide an insruction how to generate them with custom `subject` field?

**Comment by abdulla-ashurov** [comment]
1. Add implementation for converting old VID/PID to requested format by @robszewczyk when we want to add new certificates:
`1.3.6.1.4.1.37244.2.1=#130436303036` to `vid=0x6006`
2. Write unit tests.
3. Write integration tests.

**Note: We will keep the existing certificates as they are. If you want to query the old certificates, you must use the old format in the `subject` field.**

**Comment by uabjabborov** [comment]
We have two options:
1. Modifying related fields (subject, issuer, ...) of a certificate before writing it to a ledger
- pros:
    - easy to implement, requires modification only before writing the certificate
    - easy to query certificate, since the `subject` contains a more readable embedded `VID/PID` field
    - easy to write unit and integration tests
    - consistency between stored and queried certificate
- cons:
    - breaking change, because it modifies certificate before writing to a ledger
    - requires migration if we want to modify existing `testnet2.0` certificates

2. Modifying certificate query results on the fly
- pros 
    - non-breaking change, because we don't modify the state
    - does not require migration
 
- cons:
    - inconsistency between queried and stored certificate
    - error-prone because of non-trivial implementation (requires different implementations for CLI and gRPC/REST queries)
    - difficult to test

**Comment by ashcherbakov** [comment]
Our recommendation is the following:
- Implement Option 1 before the Main Net 1.0 launch
- Do not perform a migration of existing root certs in the Test Net (so that they stay as-is)
