### ISSUE TITLE
VIDs should be hexadecimal values

### ISSUE THREAD

**Issue by wc-smith** [zigbee-alliance/distributed-compliance-ledger#272]
CSA has traditionally maintained Vendor IDs (Manufacturer Codes) as hexadecimal values, see https://groups.csa-iot.org/wg/members-all/document/10905.

DCL reports, and presumably accepts, decimal values for VIDs. This discrepancy raises the prospect that incorrect values for VID might be entered, either by error in converting from hex to decimal or by misinterpreting a hex value as decimal (when all digits are less than 'A').

DCL should accept and report hex values to conform with Alliance historical precedent.

**Comment by jmeg-sfy** [comment]
+1 it should be even both way 
and VID:PID display like USB style

**Comment by hawk248** [comment]
Need more investigation.
Current VID are stored as `INT` ... changing to hex means modifying state data.

**Comment by jmeg-sfy** [comment]
maybe not the storage just the way it is displayed

**Comment by ashcherbakov** [comment]
I believe we need to apply the same change for PIDs, not for VIDs only.

**Comment by abdulla-ashurov** [comment]
We can send REST API and CLI requests in hex format:
REST API:
- dcl/model/models/0x0B816/0x1
CLI:
- dcld query model get-model --vid=0x0B816 --pid=0x1

**Comment by uabjabborov** [comment]
There are two options for this issue:
1) Keep VID/PID as integer and make conversions only on the client-side (for gRPC and REST)
- pros:
   - no breaking changes
- cons:
   - inconsistency between shown and stored data
2) Use `string` type for VID/PID
- pros:
   - full consistency between shown and stored data
   - no conversions needed on client-side
- cons:
   - breaking change, needs migration for old values
   - requires API change for gRPC/Rest
   - does not conform to DCL specification

**Comment by ashcherbakov** [comment]
Our current recommendation is to go with **Option 1** (non-breaking change), but please note that it will have the following consequences (in particular, please see the text in bold):

- Write Requests
  - CLI: possible to use VID/PID in hex in CLI tx commands (it's possible even now, no changes needed, just more tests)
  - gRPC/REST:  possible to use VID/PID in hex in CLI tx commands (it's possible even now, no changes needed, just more tests)
- Read Requests (Queries)
  - CLI: query commands will return VID/PID in hex (it will require a change in CLI)
  - REST: 
     - possible to use hex VID/PID in query URLs (for example dcl/model/models/0x0B816/0x1), so no changes needed, just more tests
     - **JSON reply will contain VID/PID in decimal format, not hex. Conversion to hex can be done on the application level.**
  - gRPC:
    -  possible to use hex VID/PID in query requests, so no changes needed, just more tests 
    - **gRPC reply will contain VID/PID in decimal format. Conversion to hex can be done on the application level.**
    
    
So, the **following changes** need to be done for that Option:
- Write unit and integration tests for hex VID/PID values in transactions and queries. We need to have integration tests for CLI, REST and gRPC.
- CLI change: post-process all query replies where VID/PID is present, and convert the VID/PID values from decimal to hex in the output JSON.

**Comment by wc-smith** [comment]
We could always ask Zigbee to update their VID table to include a decimal value column.

**Comment by robszewczyk** [comment]
> There are two options for this issue:
> 
> 1. Keep VID/PID type as an integer
> 
> * pros:
>   
>   * no breaking changes
>   * `REST` - supports hex as a path variable for queries (ex: `dcl/model/models/0x0B816/0x1`)
>   * `CLI` - supports hex as an argument (ex: `dcld query model get-model --vid=0x0B816 --pid=0x1`)
>   * `gRPC` -  generated `int` fields support `hex` value assignment
> * cons:
>   
>   * `REST` - `json` does not support `hex` values for `number` types, so query results will be in `decimal` format
>   * `CLI` - non trivial modifications are required from server side to make query responses in `hex`
>   * inconsistency between query arguments (in `hex`) and response parameters (in `decimal`) for `vid` and `pid`

At least on the input side of the CLI I would advocate for falling back onto unambiguous format for numbers and accepting commonly understood (at the very least) `1234` (no leading prefix implies decimal format) and `0x1234` (hexadecimal format).  

From brief browsing around, it looked like there are provisions for expressing hexadecimal numbers in JSON5, but that is not a likely solution for us.

**Comment by hawk248** [comment]
Now is the time to not shy from breaking changes for long term stability .. in Option 1, we will have one case where REST Api calls can lead to confusion ... for sake of consistency (same response regardless of which interface is used), I recommend option 2.

**Comment by tcarmelveilleux** [comment]
I would recommend option 1, and the confusion people may have, they will have to just take. It's not that confusing that a format that looks like a decimal number is a decimal number.

**Comment by hawk248** [comment]
TT decided on option 1. It will allow insertion using hex 0x designator for VID to suppress confusion of INT -> hex conversion during DCL key input (proposal).
Option 1 keeps INT as the internal representation and is a non breaking change.
