### ISSUE TITLE
[Get account with address] The error is returned if the `get-account-with-address` command contains the address of any proposed account.

### ISSUE THREAD

**Issue by askolesov** [zigbee-alliance/distributed-compliance-ledger#28]
Severity: major

Build info: 1b992833

Steps to reproduce:

1. Enter `get-account-with-address` command which contains the address of any proposed account.
Example of this command: `zblcli query auth account --address=<value of the proposed account>`
2. Send the command.
3. Look at the received result.

Actual results: 
The error is returned.
Please see the attachment for more details about the received error.
![image](https://user-images.githubusercontent.com/21123752/92370084-7ac23d00-f102-11ea-9622-e2c77d8fa480.png)

Expected results: 
Info about the proposed account should be returned.

Additional info:
There are no problems when the address of any approved account is used in the `get-account-with-address` request.

By @julia-aksyanova

**Comment by ashcherbakov** [comment]
A correct "Not Found" error is returned now. A proposed account can be get via `dcld query auth proposed-account --address=<>` command.
