### ISSUE TITLE
Feature: Reject a proposal

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#286]
As a Trustee, I can reject a proposal, so that once more than 1/3 of rejects is received, the proposal goes to rejected state.

Notes:
- It should not be possible to vote multiple times for the same Trustees, so once approve/reject is sent, no more votes are accepted from that Trustee
- The rejected proposal should not be removed, but kept in the state for history purposes
- All votes (rejects and approvals) must be stored and kept for the rejected proposals for the history purposes.

**Comment by hawk248** [comment]
Pre 1.0

**Comment by uabjabborov** [comment]
@abdulla-ashurov,  issue #288 seems to be related to this issue. Consider including it to implementation if applicable.

**Comment by abdulla-ashurov** [comment]
### Plan of attack for section auth:

**Create a message and a new entity:**
- Add a new command `reject-add-account` and create a new entity `RejectedAccount` with fields `Account` and `RejectApprovals`.

**Note: If we have more than 1/3 of rejects is received, the proposal goes to a new entity RejectedAccount.**


**Check:**

- A Trustee should not vote multiple times for the same account, so once approve/reject is sent, no more votes are accepted from that Trustee
- The rejected proposal should not be removed but kept in state for historical purposes.
- All votes (reject and approvals) must be stored and kept for the rejected proposals for historical purposes.
