### ISSUE TITLE
Feature: remove a proposal by the owner

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#287]
As a Trustee who did the proposal, I can remove it if there are no votes for it yet, so that proposals sent by mistake can be easily removed without requiring 2/3 of Trustees to vote reject.

Note:
- Can be done only by the Trustee who sent the proposal 
- The proposal can be just removed from the state, no need to keep it

**Comment by hawk248** [comment]
Defer until next meeting.

**Comment by hawk248** [comment]
Voting in mainnetv1.0 will allow reject during trustee approval phase.
