### ISSUE TITLE
[Add test result] Need to add the length limitation for the `test-result` field in the `add-test-result` command.

### ISSUE THREAD

**Issue by julia-aksyanova** [zigbee-alliance/distributed-compliance-ledger#3]
Severity: 
enhancement

Build info:
05059700

Overview:
Need to add the length limitation for the `test-result` field in the `add-test-result` command (
zblcli tx compliancetest add-test-result --vid=<uint16> --pid=<uint16> --test-result=<string> --test-date=<rfc3339 encoded date> --from=<account>).
Actually, the `test-result` field is not limited.
It is suggested to make the next limitation that must be discussed:
 - the maximum available length for the `test-result` field is near 255-2500 symbols.

If the mentioned parameter contains 5000 symbols, you get the following error as a result of command execution.
![image](https://user-images.githubusercontent.com/70644510/91999764-6ae2db80-ed45-11ea-91fc-5b7ce3e7289a.png)

**Comment by ashcherbakov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/199
