### ISSUE TITLE
[Add model info] Need to add the length limitation for the `name`, `description`, `sku`, `firmware-version`, `hardware-version`, `custom` fields in the add model info command.

### ISSUE THREAD

**Issue by askolesov** [zigbee-alliance/distributed-compliance-ledger#30]
Severity: 
enhancement

Build info: 
1b992833

Overview: 
Need to add the length limitation for the `name`, `description`, `sku`, `firmware-version`, `hardware-version`, `custom` fields in the add model info command (`zblcli tx modelinfo add-model --vid=<uint16> --pid=<uint16> --name=<string> --description=<string or path> --sku=<string>  --firmware-version=<string> --hardware-version=<string> --tis-or-trp-testing-completed=<bool> --from=<account>`).
Actually, name and description values are not limited. 

It is suggested to make the next limitations that must be discussed:
* the maximum available length for the `name` field is near 50 -255 symbols.
* the maximum available length for the `description` field is near 255-1000 symbols.
* the maximum available length for the `sku` field is near 50 -255 symbols.
* the maximum available length for the `firmware-version` field is near 50 -255 symbols.
* the maximum available length for the `hardware-version` field is near 50 -255 symbols.
* the maximum available length for the `custom` field is near 255 symbols.

If each of all mentioned parameters contains 2500 symbols, you get the following error as a result of command execution.
![image](https://user-images.githubusercontent.com/21123752/92370215-a9401800-f102-11ea-9313-5ccb8da8a68a.png)

By @julia-aksyanova

**Comment by ashcherbakov** [comment]
Already added to all Model fields according to the latest spec
