### ISSUE TITLE
Certificate SKID and subject should be unambiguous format for X509 transactions

### ISSUE THREAD

**Issue by tcarmelveilleux** [zigbee-alliance/distributed-compliance-ledger#301]
The fields for `*_X509_ROOT_CERT` transactions are ambiguous formatting

For example Ex: https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/transactions.md#approve_add_x509_root_cert

> Parameters:
> subject: string - proposed certificates's Subject
> subject_key_id: string - proposed certificates's Subject Key Id
>
> ...
>
> CLI command:
> dcld tx pki approve-add-x509-root-cert --subject=*<string>* --subject-key-id=*<hex string>* --from=<account>
> Validation:

The subject key ID (`subject_key_id` field) is a "hex string". This is ambiguous, especially if stored in a hex encoding.

In latest release, output for a given PAA was:

```
      {
        "subject": "CN=Matter PAA 1,O=Google,C=US,1.3.6.1.4.1.37244.2.1=#130436303036",
        "subject_key_id": "B0:0:56:81:B8:88:62:89:62:80:E1:21:18:A1:A8:BE:9:DE:93:21"
      }
```

We can see the 2nd byte (0x00) is encoded as `0` instead of `00` and 4th from last (0x09) is encoded as `9` instead of `09`. Therefore, there may be two or more ways to convey the SKID: having leading zeroes on bytes, or not, and whether it's uppercase or not.

Similarly, the subject string is a marshalling of what is given by DCL, but it's possible the marshalling done is not unambiguous, since the only unambiguous representation is ASN.1 DER octet strings. Any "human readable" version would need to be encoded not necessarily as OpenSSL formats it for output. OpenSSL formats its output  merely for convenience, NOT for canonical equivalence matching.

For example, in the above, if the CN contained commas, then the subject would be ambiguous to match between the cert and the output. There is a possibility that confusing encodings could be generated for the `subject`.

For the subject, I recommend having both `subject` and `subject_as_bytes`, where the subject field DER bytes are provided as a colon-separated hex field in `subject_as_bytes`, and the "convenience" human-readable subject is in `subject`. The transactions should take the *hex* canonical version rather than a possibly ambiguous string version.

**Comment by hawk248** [comment]
The current set of testnet PAA's will be revoked and re-submitted after this change to the testnet.

**Comment by abdulla-ashurov** [comment]
1. Update subject_key_id format (add 0 value where need for subject_key_id):
```B0:0:56:81:B8:88:62:89:62:80:E1:21:18:A1:A8:BE:9:DE:93:21``` 
to 
```B0:00:56:81:B8:88:62:89:62:80:E1:21:18:A1:A8:BE:09:DE:93:21```

2. Add and update parameters for the Certificate:

- Update parameter **subject** - type is string, use base64 text format to store certificate's original subject.

- Add parameter **subjectAsText** - type is string, need for human-readable format.


3. Update documentation

**Comment by abdulla-ashurov** [comment]
**Plan of attack:**
- Convert from der encoded issuer and subject of certificate to StringBase64 format
- Update unit and integration tests
