### ISSUE TITLE
Upgrade Cosmos SDK and Tendermint to the latest versions

### ISSUE THREAD

**Issue by uabjabborov** [zigbee-alliance/distributed-compliance-ledger#303]
Consider upgrading Cosmos SDK and Tendermint to the latest versions.
- The latest versions contain some security and bug fixes.
- Current version of Tendermint requires RPC endpoints for light client verification when state sync is enabled. Starting from v0.35.0 Tendermint can be configured to use only p2p connections.
- Careful research is needed to understand potential breaking changes.

**Comment by akarabashov** [comment]
Cosmos SDK is upgraded to v0.47.8
Tendermint replaced with CometBFT v0.37.4
Unit and integration tests are updated
Docs are updated.
