### ISSUE TITLE
typo "companyPrefferedName" in /dcl/vendorinfo/vendors

### ISSUE THREAD

**Issue by j2fong** [zigbee-alliance/distributed-compliance-ledger#312]
the response body of the vendor API /dcl/vendorinfo/vendors has a typo "companyPrefferedName" instead of "companyPreferredName"

**Comment by abdulla-ashurov** [comment]
### Corrected typo 'companyPrefferedName' to 'companyPrefferredName' for all places where use this field

**PR:**
- #335
