### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#333]
- Issue 0.10.0 Release
- Check that upgrade to 0.10.0 via cosmovisor and Propose/Approve Upgrade works 
  - Create an integration test that does the following:
     - Write all types of transactions at version 0.9.0
     - Upgrade to 0.10.0 via cosmovisor and Propose/Approve Upgrade
     - Make sure that pool is in consensus
     - Write all types of transactions
     - Make sure that pool is in consensus
  - The following helper scripts can be used for that test (we don't need to test switch_to_cosmovisor script, we can start with a cosmovisor based pool at 0.9.0):
    - https://github.com/spivachuk/distributed-compliance-ledger/blob/22bf0c529f2860f389647aac78a704f2254d7586/switch-to-cosmovisor-test-how-to.md
     - https://github.com/spivachuk/distributed-compliance-ledger/tree/env-for-switch-to-cosmovisor-test
     - https://github.com/spivachuk/distributed-compliance-ledger/tree/switch-to-cosmovisor-test

**Comment by abdulla-ashurov** [comment]
Add integration tests for upgrading v0.9.0 to v0.10.0:
https://github.com/abdulla-ashurov/distributed-compliance-ledger/tree/abdulla-ashurov/issue333
