### ISSUE TITLE
Change Vendor Account Apporval to >=1/3 Trustee approval

### ISSUE THREAD

**Issue by hawk248** [zigbee-alliance/distributed-compliance-ledger#347]
To streamline vendor account creation and approval, current 2/3+ Trustee approval is slowing vendor's ability to use testnet and will create bottleneck for production. The DCL TT decided to change it to >= 1/3 trustee approval.

No CHANGE on any other approval or revocation requirement.

**Comment by abdulla-ashurov** [comment]
Plan of attack:
- Change Vendor Account Approval to >=1/3 Trustee approval.
- Add unit and integration tests (CLI, gRPC, REST API).
- Update documentation in section `Auth` for role `Vendor`.

PR:
- #351
