### ISSUE TITLE
Rename "FirmwareDigests" to "FirmwareInformation"

### ISSUE THREAD

**Issue by tcarmelveilleux** [zigbee-alliance/distributed-compliance-ledger#354]
With spec PR https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5196, if it merges before 1.0, we have a change of field name from FirmwareDigests to FirmwareInformation.

Attached is a patch that I think would cover most of it, but I have not tried it myself.
[patch_rename_firmware_digests.zip](https://github.com/zigbee-alliance/distributed-compliance-ledger/files/8664799/patch_rename_firmware_digests.zip)

**Comment by abdulla-ashurov** [comment]
**Plan of attack:**
- Rename 'FirmwareDigests' to 'FirmwareInformation'

PR:
- #361
