### ISSUE TITLE
Add "CDCertificateID" field to `DeviceSoftwareCompliance` schema, and associated query

### ISSUE THREAD

**Issue by tcarmelveilleux** [zigbee-alliance/distributed-compliance-ledger#356]
When https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5199 lands in the spec, we would have the following changes required:

- Add mandatory `CDCertificateID` (19 character max string) to `DeviceSoftwareCompliance`
- Add a new query that can look-up all DeviceSoftwareCompliance records matching a given `CDCertificateID`

**Comment by ashcherbakov** [comment]
This will be a breaking change, so better to do it before 1.0 launch.

**Comment by abdulla-ashurov** [comment]
@tcarmelveilleux 
CDCertificateID is a unique key?

**Comment by abdulla-ashurov** [comment]
### Plan of attack:
1. Add a new entity `DeviceSoftwareCompliance` with all fields from the entity `ComplianceInfo`.
2. Add associate query with CDCertificationID for the new entity `DeviceSoftwareCompliance`.
3. Add unit and integration tests.
4. Update documentation.
