### ISSUE TITLE
Incomplete section 11.23.7 DCL DeviceSoftwareCompliance / Compliance test result Schema

### ISSUE THREAD

**Issue by hawk248** [zigbee-alliance/distributed-compliance-ledger#367]
We have received additional fields request from director of certification. They need to be added in spec and in upcoming DCL release. DCL TT will discuss this issue on May 26th 2022 meeting. The fields marked N.A. below are not in DCL and have been identified as new fields that need to be added as OPTIONAL in Compliance Schema.

From CSA Director of Cert:

Following on from the talk we had, I’ve discussed with the team and here are the fields that we’d like to have added to the DCL if they are not already present:

Certification Type (Full, CbS, CTP, PFC) – N.A.
Company Name – Can be cross refreneced from model->vendor->vendorinfo
Product Name – Name/Description is there on the device model
Program Type (Z3, ZSE, Matter, App&Component, etc) – We have a field called Certification Type (valid values are zigbee and matter)
Program Type version (1.0, 1.1, 1.2a, etc) – N.A.
Device type – Present on the model
FW version– Present on the model
HW version - Present on the model
Date Certified - Present on the certification record
Certification ID# - N.A.
Family ID# (for PFC) N.A.
Parent/Child (for PFC) N.A.
Supported Clusters N.A.
Compliant Platform used (Zigbee PRO, Thread, WiFi, etc) N.A.
Compliant Platform version N.A.
OS version (for App&Component Cert) N.A.

NOTE: CbS = Certification by Similarity, CTP = Certification Transfer Program, PFC = Product Family Certification

[11.23.7. DeviceSoftwareCompliance / Compliance test result Schema](https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/new#ref_DistributedComplianceLedger_Compliance_Schema)

**Comment by ashcherbakov** [comment]
@hawk248 Is it expected that `Certification Type` needs to be renamed to `Program Type`?

**Comment by abdulla-ashurov** [comment]
@hawk248 
1. Are CertficateID and CDCertificateID (from this ticket #356) the same fields?
2. Is Parent/Child a single field or are Parent and Child separate fields?

**Comment by abdulla-ashurov** [comment]
### Plan of attack:

1. Add these are fields:
  `Certification Type` - required, string enum (“zigbee” or “matter")
  `CDCertificationID` - required, string, max 64 characters (there will be no “Certification ID”, CDCertificationID will be used for that purpose).
  `Certification Route` - optional, string, max 64 characters
  `Program Type` - optional, string, max 64 characters
  `Program Type version` - optional, string, max 64 characters
  `Family ID` - optional, string, max 64 characters
  `Parent/Child` - optional, string enum ("parent" or “child")
  `Supported Clusters` - optional, string, max 64 characters
  `Compliant Platform used` - optional, string, max 64 characters
  `Compliant Platform version` - optional, string, max 64 characters
  `Transport`- optional, string, max 64 characters
  `OS version` - optional, string, max 64 characters
2. Add unit and integration tests.
3. Update documentation.

PR:
- #376
