### ISSUE TITLE
I wan't to crate a vendor account from testnet,but there is an error,please help,thanks!

### ISSUE THREAD

**Issue by xufangbo** [zigbee-alliance/distributed-compliance-ledger#375]
$ dcld keys add my-test-account
Enter keyring passphrase:
Re-enter keyring passphrase:
{
	"name": "my-test-account",
	"type": "local",
	"address": "cosmos13g3uk2f9kql5xreuyz7vjm36kaadmxr59z33p4",
	"pubkey": "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"AjPaoQDcXa0LDgrEsFe1C+DsWwCPq6mLzMoDFqe8cCbR\"}",
	"mnemonic": "cannon ring spring jelly muffin strike junk choice rebel chimney system spawn dog end arrange motion tribe color pattern loan tomato author mountain light"
}

$ dcld tx auth propose-add-account \
--address=cosmos13g3uk2f9kql5xreuyz7vjm36kaadmxr59z33p4 \ --pubkey="{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"AjPaoQDcXa0LDgrEsFe1C+DsWwCPq6mLzMoDFqe8cCbR\"}" \
--roles=Vendor \
--vid=4936 \
--from=my-test-account
Enter keyring passphrase:
**Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = not found: key not found**
Usage:
dcld tx auth propose-add-account [flags]

**Comment by svenehlers** [comment]
I have exactly the same issue
