### ISSUE TITLE
Error: invalid character 'k' looking for beginning of value

### ISSUE THREAD

**Issue by xwmdev** [zigbee-alliance/distributed-compliance-ledger#385]
dcld tx auth propose-add-account --address=cosmos18g40ky73s28sa3p9s52af8e97g0yq7kthfjcpa --pubkey={"@type":"/cosmos.crypto.secp256k1.PubKey","key":"Ah9z3iNx3Z+IQgBg8rgkGqy6ZmvM8wzaDUZ6gWFN+5j9"} --roles=Vendor,NodeAdmin --vid=4563 --from=jack

Error: invalid character 'k' looking for beginning of value

**Comment by svenehlers** [comment]
I had the same issue and it was solved for me by adding ' around the pubkey parameter:

--pubkey='{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"Ah9z3iNx3Z+IQgBg8rgkGqy6ZmvM8wzaDUZ6gWFN+5j9"}'
