### ISSUE TITLE
[Add test result] Need to change min and max available value for the `test-date` field.

### ISSUE THREAD

**Issue by julia-aksyanova** [zigbee-alliance/distributed-compliance-ledger#4]
Severity:
enhancement

Build info:
0505970

Overview:
Need to add the limitation for the `test-date` field in the `add-test-result` command (
zblcli tx compliancetest add-test-result --vid= --pid= --test-result= --test-date= --from=).
Actually, the `test-date` field has the following limits:
 - minimum available value is equal to `1000-01-01T00:00:00Z`;
 - maximum available value is equal to `9999-12-31T23:59:59Z`.

It is suggested to change these limitations for the following values that must be discussed:
 - minimum available value is equal to `1900-01-01T00:00:00Z`;
 - maximum available value is equal to `1999-12-31T23:59:59Z`.

**Comment by ashcherbakov** [comment]
Test Results are not stored in DCL anymore.
