### ISSUE TITLE
Deletion of Model Versions

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#421]
There is a command to delete a model, but there is no command to delete a model version.

1.  Model version can be deleted by the owner Vendor (account with the VID created the model) only before it is certified and certification is issued by CSA.
2. When a Model is deleted, the corresponding model versions must be deleted as well
3. Model can be deleted by the owner Vendor (account with the VID created the model) only before at least one of its Model Versions is certified and certification is issued by CSA.
   - Example: (A)/(B)/1.0, (A)/(B)/2.0, (A)/(B)/3.0 (Certified). In this scenario, ModelVersion (A)/(B)/(1.0 - 2.0) can be deleted. However, model (A)/(B) can not be deleted because of the certification record on (A)/(B)/3.0

  
Notes:
- The deletion must be a ~~soft-delete~~ final delete (completely remove from the State the same way as a Model)
- ~~GET_DELETED_MODEL_VERSION(s) needs to be implemented~~
- Separate PRs cane be sent for each item (1, 2, 3)
- The model/modelversion can not be deleted, if its certification status is revoked or provisioned. In other words, deletion can not happen if there is any certification status.

**Comment by lazizcodesatdsr** [comment]
FYI, @DenisRybas has initialized the deletion (https://github.com/zigbee-alliance/distributed-compliance-ledger/tree/delete-model-version)
While he is busy with another task, I will take the implementation for the point 1.
