### ISSUE TITLE
[SEEK OPEN NODES] Anyone can provide a open node?

### ISSUE THREAD

**Issue by robinmo** [zigbee-alliance/distributed-compliance-ledger#428]
Just needed for testing getting device info from DCL, many thanks.

**Comment by ashcherbakov** [comment]
You can check CSA open endpoints: https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/deployment/persistent_chains/main-net/main-net-csa-endpoints.md

**Comment by robinmo** [comment]
> You can check CSA open endpoints: https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/deployment/persistent_chains/main-net/main-net-csa-endpoints.md

Thanks @ashcherbakov I will try.

**Comment by hawk248** [comment]
No further actions here.
