### ISSUE TITLE
PKI revocation: Debug 2

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#469]
1. Enable upgrade test
2. Use instructions from https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/README-DEV.md#how-to-make-changes-in-data-model-for-existing-modules to update openapi after all changes in .proto are made. 
3. Make sure that VUE files are re-generated after changes in .proto.
4. Update the DEV instructions to reflect the move of some .pb files.
5. Update docs (transactions.md)
6. Make sure all items from https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/475 are done

**Comment by lazizcodesatdsr** [comment]
Note 1: The scripts for updating/generating the openapi docs are correct and working as expected - it is updated if and only if the `query.proto` files are updated.

**Comment by ashcherbakov** [comment]
Will be addressed in #483
