### ISSUE TITLE
Unable to write to https://testnet.iotledger.io/

### ISSUE THREAD

**Issue by absoluteabutaj** [zigbee-alliance/distributed-compliance-ledger#470]
Hello there, 

After creating a wallet, I wanted to write a new model on https://testnet.iotledger.io/, but whenever I try to write, it says `Error while processing Tx ModelInfo Tx failed`

I tried the CLI setup to write to this ledger, with the below mentioned config,

```
dcld config chain-id testnet2.0
dcld config node on.test-net.dcl.csa-iot.org:26657
```

I used this command

```
dcld tx auth propose-add-account --address=cosmos1jte6w5q94pue5uqzq27r5f0sj6e2ckff97pdnr --pubkey='{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A7usdh/624cbzRGDINao+5504TmXiaIoewakf07chfS2"}' --roles=Vendor --vid=0xFFF1 --from=ota
```
to propose an account and it returned with,
```
Error: post failed: Post "http:": http: no Host in request URL
```
I tried probing the node with `nc` and the tcp connection was successful.

What I'm missing?

**Comment by jcps07** [comment]
Was the node that you created already proposed and approved by the DCL Trustees?

Refer to [Running a Full-Node](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/running-node-manual/full-node.md) guide.

**Comment by absoluteabutaj** [comment]
@jcps07 - That's where I need help I think. How can I communicate with the Trustees? 

As far as I know, I've share the account address and the public key to the Trustees with the account role, right?

**Comment by ifdreams** [comment]
> Was the node that you created already proposed and approved by the DCL Trustees?
> 
> Refer to [Running a Full-Node](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/running-node-manual/full-node.md) guide.

I have the same question, what are the prerequisites for writing to 
testnet.iotledger.io? Join the CSA Alliance? Let me make a little complaint, the doc document is too vague, which is not conductive to the popularity of technology, and it is too unfriendly for novices

**Comment by SonicBrother** [comment]
> Was the node that you created already proposed and approved by the DCL Trustees?
> 
> Refer to [Running a Full-Node](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/running-node-manual/full-node.md) guide.

@jcps07 Does it means: Before i execute the `dcld tx auth propose-add-account` ,i should create a `Full-Node`?

**Comment by jcps07** [comment]
Only Trustees are eligible to issuing the `propose-add-account` command.
Account Roles (Trustee, Node Admin, Vendor) are independent from Full Nodes (Observer or Validator)

You may have an approved Vendor account and use a client to connect to a Full Node to query data.
You must have an approved Node Admin account to deploy a Validator Node.
