### ISSUE TITLE
How to write to the Ledger

### ISSUE THREAD

**Issue by ifdreams** [zigbee-alliance/distributed-compliance-ledger#476]
How to write to the testnet  [testnet.dcl   ](https://testnet.iotledger.io/)  ，“The DCL WebUI is an application to view and manage the information from the ledger. The DCL is permissionless for read operations and requires authorized accounts for writing operations.” 
Is this passage valid for testnet?  Do I have to join the CSA Alliance to write  testnet   ?

**Comment by ashcherbakov** [comment]
Yes, it's the same for both TestNet and MainNet. An account approved by CSA Trustees needs to be created to be able to write to the ledger.

**Comment by SonicBrother** [comment]
> How to write to the testnet [testnet.dcl ](https://testnet.iotledger.io/) ，“The DCL WebUI is an application to view and manage the information from the ledger. The DCL is permissionless for read operations and requires authorized accounts for writing operations.” Is this passage valid for testnet? Do I have to join the CSA Alliance to write testnet ?

@ifdreams  How did u write testnet? I used gRPC to query info from  code:
```java
        ManagedChannel managedChannel = ManagedChannelBuilder.forAddress("on.test-net.dcl.csa-iot.org", 26657).usePlaintext().build();
        QueryGrpc.QueryBlockingStub queryBlockingStub = QueryGrpc.newBlockingStub(managedChannel);
        QueryOuterClass.QueryGetModelRequest.Builder builder = QueryOuterClass.QueryGetModelRequest.newBuilder();
        builder.setPid(100);
        builder.setVid(31);
        QueryOuterClass.QueryGetModelRequest build = builder.build();
        QueryOuterClass.QueryGetModelResponse model = queryBlockingStub.model(build);

```
, but it is blocking in `QueryOuterClass.QueryGetModelResponse model = queryBlockingStub.model(build);` when i run this demo. Am i right? And could i have your demo code? thanks
