### ISSUE TITLE
Fix TestPkiDemo

### ISSUE THREAD

**Issue by askolesov** [zigbee-alliance/distributed-compliance-ledger#48]
This test periodically hangs up. There is also the comment here:

// FIXME: `GetX509CertChain` calls within this test may fail with EOF on an attempt to read the response
// from REST API server and so leave the resulting `Certificates.Items` slice empty.
// The issue seems to be caused by the connection being closed due to timeout while REST API server
// is gathering the reply which consists of multiple replies from the pool.
// However, `net/http.Client` does not report the request as timed out while actually it seems to be so.

**Comment by askolesov** [comment]
But it works in CI

**Comment by ashcherbakov** [comment]
Deprecated after update to the latest cosmos SDK
