### ISSUE TITLE
Getting Account testnet

### ISSUE THREAD

**Issue by SonicBrother** [zigbee-alliance/distributed-compliance-ledger#485]
![image](https://github.com/zigbee-alliance/distributed-compliance-ledger/assets/74613038/6de4d8fc-53c5-4b71-b00c-e346d1f7d4c5)

when i am getting account, where can i get the vid ,jack , alice?
thx

**Comment by meilin-shi** [comment]
have you got a trustee name? how to get it?

**Comment by jcps07** [comment]
The VID is assigned by the Alliance's Certification team. The "from" field is the name of the key in your system. Type "dcld keys list" to get the name of the key.

Only Trustees can propose and approve accounts, if you want your account to be proposed, you can reach out to dcl-admin@csa-iot.org.
