### ISSUE TITLE
[Add test result] Need to add the validation that the entered value for the `test-date` parameter is not from the future.

### ISSUE THREAD

**Issue by julia-aksyanova** [zigbee-alliance/distributed-compliance-ledger#5]
Severity:
enhancement

Build info:
0505970

Overview:
Need to add the validation that the entered value for the `test-date` parameter is not from the future.
`test-date` parameter should have the date from the past. So the user should not have any possibility to add a date from the future (tomorrow, next week/year/century, etc.).

Additional info:
This issue may affect to the https://github.com/zigbee-alliance/distributed-compliance-ledger/issues/4

**Comment by ashcherbakov** [comment]
Test Results are not stored in DCL anymore.
