### ISSUE TITLE
how to getting account in testnet

### ISSUE THREAD

**Issue by meilin-shi** [zigbee-alliance/distributed-compliance-ledger#508]
when i am getting a account in testnet2, i need a trustee. how to get a trustee, is there any documents? 
thank you

**Comment by jcps07** [comment]
Why do you need an account with Trustee role? Have you checked the DCL Whitepaper to get a better understanding of the Roles.
https://csa-iot.org/developer-resource/white-paper-distributed-compliance-ledger/

**Comment by meilin-shi** [comment]
thank you for your reply, I may have expressed myself incorrectly.  I just need an account with Vendor role, but when I run the command line `dcld tx auth propose-add-account `,  It takes a parameter called --from, the parameter represents a Trustee name.

**Comment by meilin-shi** [comment]
I got it at another issue.
