### ISSUE TITLE
[DCL REST API] Query the Matter PAA certificate with only subjectKeyId

### ISSUE THREAD

**Issue by wqx6** [zigbee-alliance/distributed-compliance-ledger#519]
Now we can query a certain Matter PAA certificate with DCL REST APIs if we have both subject and subjectKeyId or only subject of that PAA certificate.
```
curl -X 'GET' 'https://on.dcl.csa-iot.org/dcl/pki/certificates/{subject}/{subjectKeyId}'

curl -X 'GET' 'https://on.dcl.csa-iot.org/dcl/pki/certificates/{subject}'
```
Could we have a DCL REST API that can be used to query PAA certificate with only subjectKeyId? Like this:
```
curl -X 'GET' 'https://on.dcl.csa-iot.org/dcl/pki/certificates?subjectKeyId={subjectKeyId}'
```

**Comment by jcps07** [comment]
DCL-TT: Recommended for 1.3

**Comment by ashcherbakov** [comment]
What is important here:
We will need to write a migration script for existing PAAs (on TestNet and MainNet) which will be executed during upgrade. The migration script should construct the new index to allow querying by SKID.

**Comment by akarabashov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/issues/519

**Comment by akarabashov** [comment]
- Functionality implemented as described in the ticket
- Unit and integration tests are added
- Implemented Store Migration
- Docs are updated

**Comment by wqx6** [comment]
@ashcherbakov  Hi, is the new REST API of querying PAA with SKID available now? If yes, how can I use the API. I didn't see update in https://on.dcl.csa-iot.org/

**Comment by ashcherbakov** [comment]
It's implemented, but not deployed to TestNet and MainNet yet.
You can look at the API at https://zigbee-alliance.github.io/distributed-compliance-ledger/
