### ISSUE TITLE
How to complete the step Attest Device Compliance if I'm a vendor

### ISSUE THREAD

**Issue by meilin-shi** [zigbee-alliance/distributed-compliance-ledger#520]
How to complete the step Attest Device Compliance if I'm a vendor and the persistent-chain is testnet-2.0 ?
Do I need to contact a third party testing organisation, how to contact to them?

**Comment by jcps07** [comment]
The Authorized Test Labs can provide guidance about their processes for certification tests. See https://csa-iot.org/certification/testing-providers/.
If you want to run tests in Test-Net prior going to the ATL, you can request the Alliance to propose your Vendor account for testing. This is available to Alliance members only. 
For follow up questions , you can send an email to help@csa-iot.org.
