### ISSUE TITLE
The CommissioningModeInitialStepsHint is set to 0 by default

### ISSUE THREAD

**Issue by jcps07** [zigbee-alliance/distributed-compliance-ledger#522]
According to the Matter Specification, section 5.7.1:

>     The Distributed Compliance Ledger entries for Standard Commissioning Flow devices SHALL include the CommissioningCustomFlow field set to '0 - Standard' and the CommissioningModeInitialStepsHint field set to a non-zero integer value, with bit 0 (Power Cycle) being set to 1.

The default value appears to be "0", and most of entries have this value set to 0, even while using "CommissioningCustomFlow" = 0. 

Propose to set the default value to "1", instead of "0".

Possible workaround: Set the value for CommissioningModelInitialStepsHitto to "1" by default, in the Web UI.

**Comment by akarabashov** [comment]
After discussion, it has become clear that the following actions are required to resolve the issue:

- Validation Implementation: Add a validation to ensure that when CommissioningCustomFlow is set to 0, CommissioningModeInitialStepsHint must not be 0.
- Data Migration: Correct previously created models where both CommissioningCustomFlow and CommissioningModeInitialStepsHint were set to zero.

**Comment by ashcherbakov** [comment]
Decisions on DCL TT call:

- Starting 1.4, default will be 0, 1 (Power Cycle).
- Make `CommissioningModeInitialStepsHint` mutable. Update the Spec. 
- The current wrong entries with 0,0 will be fixed by asking members to update this field for data after to 1.4 (once it's made mutable).

This will avoid complex migration and mutation of data which we should not do.

**Comment by akarabashov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/562

- Functionality implemented as described in the task.
- Unit and integration tests are added.
- Docs are updated.
