### ISSUE TITLE
Instruction to use HSM with DCL UI and Keppler

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#525]
- Check that Ledger Nano works with DCL UI (Keppler)
- Check that Ledger Nano works with DCL CLI
- Prepare instructions

**Comment by akarabashov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/569

- Checked that Ledger Nano works with DCL
- Prepared instruction: https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/ledger-nano.md
