### ISSUE TITLE
Getting error on replay: wrong Block.Header.AppHash. while trying to run the full node

### ISSUE THREAD

**Issue by schinmay** [zigbee-alliance/distributed-compliance-ledger#533]
After about 6 minutes of dcld node running and syncing up, we are getting the error "Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 863536F4B5AC194020C5A568E9CB1C5241B418E2753823E40088B8A7AF74FD0B, got 480D25B8475DA40AC0E318A5D3F0A64A0D4C0BA92E3F281C8BB37863375758AB" multiple times and the node is no longer accessible.

**Comment by ashcherbakov** [comment]
What release/version is used here? As the previous release/update had breaking changes, please make sure that one of the methods mentioned https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/advanced/running-node-in-existing-network.md is used for a new node.

**Comment by hawk248** [comment]
Closing .. as there is a known state sync issue that must be addressed for new nodes. This was fixed in DCL 1.2.

**Comment by Chapoly1305** [comment]
I don't understand why I am still running into this issue using latest commit.
