### ISSUE TITLE
Add custom flow capability for commissioners without local UI

### ISSUE THREAD

**Issue by tleacmcsa** [zigbee-alliance/distributed-compliance-ledger#538]
Commissioners that do not have a local user interface (visual or vocal) need a facility to enable a remote device on the operational network, such as a mobile phone, to present an interactive user interface to the user on behalf of the commissioner. 

One way to do this is to provide information similar to the Pairing Hint for commissionable devices in the DNS-SD TXT payload returned from commissioner discovery.  This commissioner hint would indicate that a custom commissioner flow should be used, which would trigger the commissionee to look up and open the related URL from the DCL.  The commissionee could choose to provide its own setup code information to this URL, which might be generated for the particular operation and/or with expiration.

Clearly this would only work for commissionees that are already on the operational network due to discovery of the commissioner, access to the DCL, and invocation of the commissioner's URL.

Changes requested include:
- update DCL DeviceModel schema to include a new optional URL that a commissionee would use to show a custom flow UI for the commissioner
- update Commissioner Discovery to include a new optional DNS-SD TXT key/value pair that would indicate to a client that the DCL should be referenced for a commissioner custom flow URL.

**Comment by ashcherbakov** [comment]
Proposal
Add a new optional field `string CommissioningCustomUIUrl` to the `Model` .proto.

**Comment by ashcherbakov** [comment]
UPDATE: the new optional field name: ` string CommissionerCustomFlowUrl`

**Comment by tleacmcsa** [comment]
Update:  The latest optional field name (renamed to reduce confusion): `string CommissionerRemoteUiFlowUrl`

>

**Comment by akarabashov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/555

- Added a new `CommissionerRemoteUiFlowUrl` field to the DCL Model schema
- Unit and integration tests are updated
- Docs are updated.
