### ISSUE TITLE
As a user, I need to be able to get the information about the created account even if the account is revoked

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#54]
Currently revoked accounts are removed from the state. But all the entities created by this account are considered as valid, but with unknown owner/creator.
As a user, I need to be able to get the information about the creator account even if the account is revoked.

**Options:**
- O1: Add a new entity `RevokedAccount`. Create a new Revoked Account when deleting an Account. Support queries for RevokedAccount(s).
- O2: Add a `revoked` flag for the current `Account` entity. Toggle the flag on revocation instead of removing the account.

**Notes**
1.  We need to make sure that it's not possible to send a transaction signed by a revoked account. 
2. We need to support re-adding of a revoked account (via a usual propose/approve account requests). So, the chosen option must support it.

**Comment by abdulla-ashurov** [comment]
Plan regarding Note 1:
1. Add a new entity for saving Revoked Account
2. When revoking an account, if we get enough votes for deletion, then that account will be saved in map Revoked Account, then we revoked that account.
3. Add query for getting specific revoked accounts and all revoked accounts.

**Comment by abdulla-ashurov** [comment]
Plan regarding Note 2:
1. Add submenu for re-adding of revoked account:
    1. propose-re-adding-revoked-account
        1. Get address, pubkey, roles, vid, approvals of RevokedAccount for propose-re-adding-account
    2. approve-re-adding-revoked-account
        1. Get the address of RevokedAccount for approve-re-adding-account

**Comment by hawk248** [comment]
Post Mainnet 1.0
