### ISSUE TITLE
New fields for Enhanced Setup Flow

### ISSUE THREAD

**Issue by koosc** [zigbee-alliance/distributed-compliance-ledger#547]
New fields will need to be added to support the Enhanced Setup Flow. These will contain fields in DeviceModel to identify the options to use for the flow and a new Schema to support storage of the texts that will be used for this flow.

PR in progress: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8944

DCL Changes: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8944/files#diff-340658b1e5339d59a1bc5b917afe73349e7ef74f0d5e79f3475e5474c35c520a

**Comment by akarabashov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/577
- Functionality implemented as described in the specification
- Unit and integration tests are added
- Docs are updated.
