### ISSUE TITLE
SchemaVersion of DAC PKI Revocation Distribution Point schema did not get bumped after #557

### ISSUE THREAD

**Issue by tcarmelveilleux** [zigbee-alliance/distributed-compliance-ledger#566]
PR #557 added a field to the CRL distribution point schema (`CRLSignerDelegator`) but the SchemaVersion was not bumped. https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/9126 will bump the version, but it has to be bumped also in the DCL implementation.

**Comment by akarabashov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/572

The default version of SchemaVersion for PkiRevocationDistributionPoint is set to 1
