### ISSUE TITLE
Validate "OtaChecksum" is base64 encoded when adding a Model-Version entry

### ISSUE THREAD

**Issue by jcps07** [zigbee-alliance/distributed-compliance-ledger#570]
From conversation in [PR #33256](https://github.com/project-chip/connectedhomeip/pull/33256): 

> [May 1, 2024](https://github.com/project-chip/connectedhomeip/pull/33256#discussion_r1586439969)
> 
> We've seen a few cases where a software update is posted in the DCL and the OtaChecksum is not base64 encoded. What do you think about adding a test that verifies at least that all the software versions for this device model have a correctly formatted checksum? Could potentially also verify other fields as well but this one in particular feels especially important.

I'd be good to add this validation at dcld stage, as it's a requirement by the Matter Spec:

> OtaChecksum
> OtaChecksum SHALL contain the digest of the entire contents of the associated OTA Software
> Update Image under the OtaUrl field, encoded in base64 string representation. The digest SHALL
> have been computed using the algorithm specified in OtaChecksumType. This field SHALL be provided
> if the OtaUrl field is populated.

**Comment by akarabashov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/issues/570

- Added validation to ensure that 'OtaChecksum' field is base64 encoded data
- Unit and integration tests are added
- Docs are updated
