### ISSUE TITLE
Rename CommissionerRemoteUiFlowUrl to ManagedAclExtensionRequestFlowUrl and update description

### ISSUE THREAD

**Issue by tleacmcsa** [zigbee-alliance/distributed-compliance-ledger#575]
`string CommissionerRemoteUiFlowUrl` should be renamed to `string ManagedAclExtensionRequestFlowUrl`.  The updated description can be found here: 

https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/9209/files#diff-340658b1e5339d59a1bc5b917afe73349e7ef74f0d5e79f3475e5474c35c520a

**Comment by hawk248** [comment]
DCT TT is taking this up and will provide feedback. But will likely be addressed before DCL 1.4 release.

**Comment by akarabashov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/576

- `CommissionerRemoteUiFlowUrl ` renamed to `ManagedAclExtensionRequestFlowUrl `
- Unit and integration tests are added
- Docs are updated.
