### ISSUE TITLE
Bring NOC Intermediate (ICAC) query in parity with Noc Root (RCAC) query

### ISSUE THREAD

**Issue by hawk248** [zigbee-alliance/distributed-compliance-ledger#582]
There needs to be parallel lookup for ICAC (NOC ICA) using vid+skid similar to GET_NOC_ROOT_BY_VID_AND_SKID (https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/transactions.md#get_noc_root_by_vid_and_skid).

**Comment by ashcherbakov** [comment]
Done in https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/584
