### ISSUE TITLE
Deleting a Model-Version doesn't fully remove it from the Model

### ISSUE THREAD

**Issue by jcps07** [zigbee-alliance/distributed-compliance-ledger#598]
Deleting a Model-Version created under a Model doesn't correctly delete it because it can still be queried in the "versions" supported by that Model. This results in an error when trying to delete a Model after deleting one of its Model-Versions.

1. Add a Model
2. Add two Model-Versions -> add [0, 1]
3. Query all-model-versions of that model -> [0, 1]
4. Delete a Model-Version -> delete [1]
5. Query all-model-versions of that model -> [0, 1]
6. Delete model (It will still have 1 model-version ok, and another "ghost") -> "failed to execute message; message index: 0: No model version associated with vid=12288, pid=70 and softwareVersion=1 exist on the ledger: model version does not exist"
7. To delete the model, I'll need to add back that "ghost" model version  ->  add [1] again, it can be dummy as long as the Software Version matches the original that was deleted before.

**Comment by jcps07** [comment]
Hello @ashcherbakov. DCL-TT agreed to include the fix in v1.4 release.
Thank you.

**Comment by ashcherbakov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/599

**Comment by jcps07** [comment]
@ashcherbakov , I just confirmed that part of the issue is still present in current version (DCL v1.5.2):
- After removing the Model-Version, it still appears when querying all Versions of the Model (i.e. `https://on.test-net.dcl.csa-iot.org/dcl/model/versions/<vid>/<pid>`), but it doesn't appear in the Web UI.
- Now the model can be deleted even when that "ghost" record remains there

**Comment by jcps07** [comment]
Unable to reproduce on new entries.
