### ISSUE TITLE
Error when creating a Model with only mandatory fields filled in

### ISSUE THREAD

**Issue by eHammarstrom** [zigbee-alliance/distributed-compliance-ledger#608]
When creating a model and only filling in the fields marked as required I get:

```
Could not broadcast Tx: Broadcasting transaction failed with code 2 (codespace: sdk). Log: Mismatched "*types.MsgCreateModel": {TagNum: 20, GotWireType: "varint" != WantWireType: "bytes"}: tx parse error
```

Is this a bug in the UI?

Tennessee Carmel-Veilleux mentioned that "Field 20 is the `enhancedSetupFlowTCUrl` in the  `MsgCreateModel`" and that it _may_ be a bug in the UI.

**Comment by ankur325** [comment]
This issue is now resolved in UI deployed at https://testnet.iotledger.io/
