### ISSUE TITLE
Maintain compatibility with 1.2 release of the API

### ISSUE THREAD

**Issue by robszewczyk** [zigbee-alliance/distributed-compliance-ledger#610]
## Problem

In generic APIs for getting certificates are expected to return the certificates from the DA PKI.  To that end, in 1.2:

* `GET /dcl/pki/certificates` returns a list of certificates 
* `GET /dcl/pki/certificates/{subject}` returns a list of certificates by subject 
* `GET /dcl/pki/certificates/{subject}/{skid}` returns a certificate for a subject and SKID

The crititical problem is that a 1.2 client would never look at the new fields added in [Certificate.proto](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/proto/zigbeealliance/distributedcomplianceledger/pki/certificate.proto) and thus not be aware that the returned values have different semantics.

## Proposed resolution

* the existing APIs for certificates continue to return certificates from the DA PKI with old semantics
* we create a new set of endpoints e.g. `certificates2` that have the semantics of getting all certificates

**Comment by hawk248** [comment]
In in DCL 1.2 -> `/dcl/pki/root-certificates` : Returns all PAA.
In in DCL 1.4 -> `/dcl/pki/root-certificates` : Returns all PAA.

**Comment by hawk248** [comment]
Update `/dcl/pki/certificates` in 1.4 so that it will ONLY return PAA, PAI and DAC (if PAI and DAC) have been uploaded in device attestation chain.

**Comment by hawk248** [comment]
Addressed as part of #612
