### ISSUE TITLE
Getting certificate information from different lists or all (follow up from #610)

### ISSUE THREAD

**Issue by jcps07** [zigbee-alliance/distributed-compliance-ledger#612]
In addition to what is requested in issue #610:

> Update /dcl/pki/certificates in 1.4 so that it will ONLY return PAA, PAI and DAC if PAI and DAC have been uploaded in device attestation chain.
> Implement another API that returns certificates regardless of PKI chain e.g. inclusive of DA or NOC.

To also consider getting certificate from Node Credentials based on Subject and/or SKID, so it'd be something like this:
| API | Description |
| ---- | ---- |
| /dcl/pki/certificates | Query certificate by Subject and/or SKID in Device Attestation list (PAA, PAI, DAC) (#610) |
| /dcl/pki/all-noc-certificates | Query certificate by Subject and/or SKID in all Node Credentials list (RCAC, ICA, NOC). <br>**Not just from specific VID** as `/dcl/pki/noc-certificates/{vid}/{subject_key_id}` does already  |
| /dcl/pki/all-certificates | Query certificate by Subject and/or SKID from Device Attestation and Node Credentials (#610) | 

All of these will get matching cert(s) of different types of certs (PAA/PAI/DAC or RCAC/ICA/NOC or both), not just Roots.

**Comment by jcps07** [comment]
Note: The proposed query is still to be triaged. (/dcl/pki/all-certificates)

**Comment by hawk248** [comment]
`/dcl/pki/all-certificates` is it needed? 
Use case: Given a SKI, allow user to query DCL to find out it it exists and what type it is.
This can be deferred. May be useful in the future.

DCL TT - OK to proceed implementation on this issue.
