### ISSUE TITLE
[Forign keys] Issue with compliance

### ISSUE THREAD

**Issue by askolesov** [zigbee-alliance/distributed-compliance-ledger#65]
Steps to reproduce:
* Create model info
* Create compliance for the model info
* Remove the model info
* Go to compliance page, click on the compliance

Result:
* Page not found error in console

Expected result:
* Good solution: implement logical deletion for model infos
* Really bad solution: show the corresponding error message

**Comment by ashcherbakov** [comment]
Related to the outdated and not supported UI, closing.
