### ISSUE TITLE
Extend the Model Info Schema to match the Spec

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#76]
**Acceptance Criteria:**
Make sure that the DCL ModelInfo fields match the spec from https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DistributedComplianceLedger.adoc
In particular,
- Allow editing of versions for the same VID/PID (will be done in https://github.com/zigbee-alliance/distributed-compliance-ledger/issues/75)
- Add the following fields:
  - ProductName
  - OtaBlob
  - CommissioningCustomflow
  - CommissioningCustomflowUrl
  - CommissioningModeInitialStepsHint
  - CommissioningModeSecondaryStepsHint
  - ReleaseNotesUrl
  - UserManualUrl
  - SupportUrl
  - ChipBlob
- Rename the following fields:
  - FirmwareVersion -> SoftwareVersionNumber + SoftwareVersionString
  - HardwareVersion-> HardwareVersionNumber+ HardwareVersionString
  - Custom -> VendorBlob
- Make sure all fields are in the same registry as in the Spec (camel case)

**Comment by ankur325** [comment]
Following PR updates the Model Schema https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/86

**Comment by ashcherbakov** [comment]
PR: #91
