### ISSUE TITLE
Add support for "confidenttial until launch" use case

### ISSUE THREAD

**Issue by piotr-polak** [zigbee-alliance/distributed-compliance-ledger#83]
Allow Vendor to submit the transactions on behalf of TestHouse and ZBCertificationCenter.
This would allow a vendor to chose a date for a product to be introduced to the public.

**Comment by ashcherbakov** [comment]
It's already supported.
- ZBCertificationCenter creates and signs a txn, but doesn't broadcast it to the ledger. The signed txn is sent to the Venodr instead.
- Vendor broadcasts the signed ZBCertificationCenter txn when the desired date comes.

How to sign but not broadcast a txn: https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/transactions.md#how-to-write-to-the-ledger
