### ISSUE TITLE
[Certify model] Need to add the length limitation for the `reason` field in the `certify-model` command.

### ISSUE THREAD

**Issue by julia-aksyanova** [zigbee-alliance/distributed-compliance-ledger#9]
Severity:
enhancement

Build info:
0505970

Overview:
Need to add the length limitation for the `reason` field in the `certify-model` command (`zblcli tx compliance certify-model --vid=<uint16> --pid=<uint16> --certification-type=<zb> --certification-date=<rfc3339 encoded date> --reason=<resaon_info> --from=<account>`).
Actually, the`reason` field is not limited.
It is suggested to make the next limitation that must be discussed:
- the maximum available length for the `reason` field is about 255-15000 symbols.

If the mentioned parameter contains 20000 symbols, you get the following error as a result of command execution.
![image](https://user-images.githubusercontent.com/70644510/92102258-0bd5a300-ede7-11ea-844c-b0a7ebb3e875.png)

**Comment by ashcherbakov** [comment]
PR: https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/199
