### ISSUE TITLE
Investigate peermissioned launch of Observer Node

### ISSUE THREAD

**Issue by hawk248** [zigbee-alliance/distributed-compliance-ledger#93]
So that we have a control on how many ON's are being created and adding load on the MainNet.

**Comment by ashcherbakov** [comment]
Any validator node can control what (and hence how many) observer nodes are connected to the given validator nodes by configuring firewall rules in such a way, that only given Observer nodes (domains or IPs) are whitelisted. A connection from an unknown Observer node will be rejected on the firewall level.


More detailed recommendations and more experiments will be done in the scope of #100.
